// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Textile, Inc.
//! Generate a `docker-compose.yml` for the whole fleet.
//!
//! Strictly one-way. The panel never reads a compose file back, and never edits
//! one in place: doing that would mean parsing YAML the operator hand-wrote,
//! losing their anchors and comments, and handing back something they no longer
//! recognise. Instead the export is a fresh, canonical file, and its header says
//! so.
//!
//! The reason it exists is recovery. Everything the panel manages lives in
//! containers and config directories, both of which outlive the panel — but
//! rebuilding a fleet from `docker run` invocations by hand is miserable. With
//! this file an operator can bring the whole fleet back with `docker compose up
//! -d` on a fresh host, panel or no panel.
//!
//! It is canonical rather than a byte-for-byte capture: services are rendered
//! from each bot's config the way the panel would create it, so an adopted bot
//! with an unusual hand-written service comes out normalised. Mounts are the
//! exception — they're rendered from the layout the bot actually has, because a
//! bot on the flat layout normalised to per-bot directory paths would name
//! directories that don't exist and fail to start. Anything the panel could not
//! represent faithfully is called out in a comment instead of being quietly
//! dropped.

use std::path::{Path, PathBuf};

use crate::panel::config::PanelConfig;
use crate::panel::docker::STOP_GRACE_SECS;
use crate::panel::inventory::{Bot, Fleet, Layout, Origin};
use crate::panel::naming::{container_name, validate_bot_id};
use crate::panel::provision::{image_of, mounts_for, signer_runtime_at};

/// Compose profile holding back the bots that weren't running at export time.
/// Named for what it means, because the operator sees it on the command line.
const STOPPED_PROFILE: &str = "stopped";

/// Render the fleet as a compose file.
pub fn render(fleet: &Fleet, cfg: &PanelConfig) -> String {
    let mut out = String::new();
    out.push_str(&header(fleet));
    out.push_str(&anchor(cfg));
    out.push_str("\nservices:\n");

    let mut rendered = 0usize;
    for bot in fleet.bots() {
        match service(bot, cfg) {
            Ok(block) => {
                out.push_str(&block);
                rendered += 1;
            }
            Err(reason) => {
                out.push_str(&format!(
                    "  # {} was not exported: {reason}\n",
                    yaml_comment(&bot.name)
                ));
            }
        }
    }
    if rendered == 0 {
        out.push_str("  {} # no bots to export yet\n");
    }
    out
}

fn header(fleet: &Fleet) -> String {
    format!(
        "# Generated by the Stitch admin panel. {} bot(s).\n\
         #\n\
         # This file is written fresh every time you export it. The panel never reads it\n\
         # back and never edits it in place, so anything you add here is yours to keep\n\
         # track of — the next export will not preserve it.\n\
         #\n\
         # What it's for: recovery. Copy it next to your bot directories and run\n\
         # `docker compose up -d` to rebuild the whole fleet on a fresh host, with or\n\
         # without the panel.\n\
         #\n\
         # Bring the fleet up:      docker compose up -d\n\
         # Add or change one bot:   docker compose up -d <bot-name>\n\
         #\n\
         # Bots that were not up when this was exported carry\n\
         # `profiles: [{STOPPED_PROFILE}]`, so the command above leaves them stopped — a bot\n\
         # someone stopped deliberately should not come back on the book by itself. A bot\n\
         # Docker was restarting counts as up: it was meant to be running, and this file\n\
         # is often how you recover onto a host where it finally will.\n\
         # Start a held-back one with `docker compose --profile {STOPPED_PROFILE} up -d <bot-name>`.\n\
         #\n\
         # A bot with its own directory has it mounted read-write at /home/stitch/run,\n\
         # which is what keeps its slot-nonce ledger on the host across container\n\
         # recreation. The config and the signer secret are re-mounted read-only on top.\n\
         # Those directories must be owned by uid 1000 so the container user can write.\n\
         #\n\
         # A bot still on the flat file layout is exported as it runs today: its config\n\
         # and key mounted individually, no writable directory, so its ledger stays\n\
         # inside the container and is lost on recreation. Migrate it in the panel to\n\
         # move it onto the host.\n",
        fleet.len()
    )
}

/// The shared settings block. Bots reference it with a YAML merge key, which is
/// what the hand-written production file does, so an operator reading the export
/// sees a familiar shape.
fn anchor(cfg: &PanelConfig) -> String {
    format!(
        "\nx-stitch: &stitch\n\
         \x20 image: {}\n\
         \x20 restart: unless-stopped\n\
         \x20 # The bot only checks for shutdown between ticks, so compose's default\n\
         \x20 # 10s would kill it mid-tick.\n\
         \x20 stop_grace_period: {STOP_GRACE_SECS}s\n\
         \x20 logging:\n\
         \x20   driver: json-file\n\
         \x20   options:\n\
         \x20     max-size: \"10m\"\n\
         \x20     max-file: \"5\"\n",
        yaml_scalar(&cfg.bot_image)
    )
}

/// Where this bot's files sit, as the compose file will name them, plus a comment
/// when that path needs explaining.
///
/// The operator is told to put the file beside their bot directories, so a relative
/// path is what makes the export portable. But the directory name is *not* the bot
/// name: an adopted compose service called `foo` can mount `<bots root>/custom`, and
/// inventory names the bot after the service. Synthesising `./foo` from the name
/// produced a recovery file whose config and secret paths simply don't exist —
/// nothing is renamed or copied at export time.
///
/// So the path comes from the mount the bot actually has. A config outside the bots
/// root can't be expressed relative to the file at all, and there the absolute host
/// path is the only faithful answer: it works on this host, which is the one being
/// recovered most of the time. It gets a comment, because it's also the one line in
/// the file that won't survive being copied somewhere else.
fn mount_base(bot: &Bot, cfg: &PanelConfig) -> (PathBuf, Option<String>) {
    // A flat-layout bot's files sit loose in the root next to everyone else's, so
    // the compose file's own directory is the base.
    if bot.layout == Layout::FlatFiles {
        return (PathBuf::from("."), None);
    }
    let Some(dir) = bot.config_host_path.as_ref().and_then(|p| p.parent()) else {
        // No mount to read: fall back to the panel's own naming, which is right for
        // every bot the panel created.
        return (Path::new(".").join(&bot.name), None);
    };
    match dir.strip_prefix(&cfg.host_bots_dir) {
        Ok(rest) => (Path::new(".").join(rest), None),
        Err(_) => (
            dir.to_path_buf(),
            Some(format!(
                "    # Its config lives at {} on the host, outside {}, so this mount is an\n\
                 \x20   # absolute path. It will not follow this file to another machine — copy\n\
                 \x20   # the directory and edit the path if you're recovering elsewhere.\n",
                yaml_comment(&dir.display().to_string()),
                yaml_comment(&cfg.host_bots_dir.display().to_string()),
            )),
        ),
    }
}

/// One service block, or the reason this bot can't be represented.
fn service(bot: &Bot, cfg: &PanelConfig) -> Result<String, String> {
    // A compose service key and a container name have to be safe, and an adopted
    // bot's name came from someone else's compose file rather than our validator.
    validate_bot_id(&bot.name)
        .map_err(|e| format!("its name isn't usable as a compose service ({e})"))?;

    let config = bot
        .config_panel_path
        .as_ref()
        .ok_or_else(|| "the panel can't read its config file".to_string())?;
    // A guess here would be worse than an omission. Exporting a Turnkey bot with the
    // hot wallet's mounts and env produces a service block that looks fine, restores
    // fine, and then can't start — and the operator only finds out on the fresh host
    // they're recovering onto. `render` turns this into a `# <bot> was not exported:`
    // line, which is a problem they can see and fix.
    let signer = signer_runtime_at(config).map_err(|e| {
        format!(
            "the panel can't tell which signer it uses, so exporting it would bake in the \
                 wrong secret and environment ({e:#})"
        )
    })?;
    let (base, base_note) = mount_base(bot, cfg);
    let mounts = mounts_for(bot, &base, &signer)?;

    let mut block = format!(
        "  {}:\n    <<: *stitch\n    container_name: {}\n",
        bot.name,
        yaml_scalar(&container_name(&bot.name))
    );

    // The anchor carries the panel's image; a bot running something else keeps it,
    // so recovering from this file doesn't swap its trading binary.
    let image = image_of(bot, cfg);
    if image != cfg.bot_image {
        block.push_str(&format!("    image: {}\n", yaml_scalar(&image)));
    }

    if let Origin::Compose { project, .. } = &bot.origin {
        let which = project.as_deref().unwrap_or("unknown");
        block.push_str(&format!(
            "    # Adopted from compose project \"{}\".\n",
            yaml_comment(which)
        ));
    }
    // A bot that wasn't up was down for a reason, and `docker compose up -d` starts
    // every service it can see. A compose profile keeps the service definition intact
    // while leaving it out of the default set, so recovering the fleet restores the
    // fleet's state rather than putting a bot someone stopped back on the book.
    //
    // `wants_to_be_up` rather than `is_running`, so a crash-looping bot is exported
    // as part of the default set: `restarting` isn't quoting this instant, but it's a
    // bot the operator means to have up, and holding it back would quietly not bring
    // it back on the host they're recovering onto.
    if !bot.state.wants_to_be_up() {
        block.push_str(&format!(
            "    # Not running when this was exported ({}), so it is held back from\n\
             \x20   # `docker compose up -d`. Start it with:\n\
             \x20   #   docker compose --profile {STOPPED_PROFILE} up -d {}\n\
             \x20   profiles: [{STOPPED_PROFILE}]\n",
            yaml_comment(bot.state.as_str()),
            yaml_comment(&bot.name)
        ));
    }

    if let Some(note) = &base_note {
        block.push_str(note);
    }

    if bot.layout == Layout::FlatFiles {
        block.push_str(
            "    # Kept on the flat file layout, so this comes back exactly as it runs today.\n\
             \x20   # Its nonce ledger lives inside the container and is lost on recreation:\n\
             \x20   # migrate it in the panel to move it onto the host.\n",
        );
    }

    block.push_str("    environment:\n      RUST_LOG: info\n");
    for var in &signer.env {
        // Signer env is generated as KEY=value; compose wants a mapping.
        if let Some((key, value)) = var.split_once('=') {
            block.push_str(&format!("      {key}: {}\n", yaml_scalar(value)));
        }
    }

    block.push_str("    volumes:\n");
    for m in &mounts {
        let spec = m
            .to_bind_string()
            .map_err(|e| format!("one of its mounts can't be expressed in compose ({e})"))?;
        // Only the writable directory mount earns the note, and a flat-layout bot
        // doesn't have one — which is exactly why its ledger doesn't survive.
        let note = if m.read_only {
            ""
        } else {
            " # rw: persists the nonce ledger across restarts"
        };
        block.push_str(&format!("      - {}{note}\n", yaml_scalar(&spec)));
    }
    block.push('\n');
    Ok(block)
}

/// Quote a YAML scalar when it would otherwise be ambiguous.
///
/// Compose values here are image refs, paths and env values. The risky ones are
/// values that YAML would read as a number, a bool, or null, and values with
/// leading/trailing space or a character that starts a YAML construct.
fn yaml_scalar(value: &str) -> String {
    let needs_quotes = value.is_empty()
        || value != value.trim()
        || value.parse::<f64>().is_ok()
        || matches!(
            value.to_lowercase().as_str(),
            "true" | "false" | "yes" | "no" | "on" | "off" | "null" | "~"
        )
        || value.starts_with(['&', '*', '!', '%', '@', '`', '>', '|', '{', '[', '?', '-', '#'])
        || value.contains(": ")
        || value.contains(" #")
        || value.contains('\n')
        // A bare scalar containing a quote is legal YAML, but quoting it anyway
        // keeps one escaping rule instead of two.
        || value.contains('\'')
        || value.contains('"');
    if needs_quotes {
        // Single quotes are YAML's literal form; the only escape needed is a
        // doubled quote.
        format!("'{}'", value.replace('\'', "''"))
    } else {
        value.to_string()
    }
}

/// Make a value safe to interpolate into a `#` comment line: a newline would end
/// the comment and turn the rest into YAML.
fn yaml_comment(value: &str) -> String {
    value.replace(['\n', '\r'], " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::panel::docker::fake::{container, dir_layout_mounts, flat_layout_mounts};
    use crate::panel::docker::ContainerState;
    use crate::panel::inventory::discover;
    use crate::panel::naming::{LABEL_BOT, LABEL_COMPOSE_PROJECT, LABEL_COMPOSE_SERVICE};
    use crate::setup;
    use std::path::PathBuf;

    fn test_cfg(tag: &str) -> (PanelConfig, PathBuf) {
        let root = std::env::temp_dir().join(format!(
            "stitch-panel-compose-{}-{}",
            std::process::id(),
            tag
        ));
        std::fs::create_dir_all(&root).unwrap();
        let mut cfg = PanelConfig::for_test(root.clone(), "/host/stitch");
        cfg.bot_image = "ghcr.io/textile-protocol/textile-stitch:sha-abc123".into();
        (cfg, root)
    }

    fn seed(root: &Path, name: &str) {
        let corridor = setup::find_corridor("cngn-usdt-bsc").unwrap();
        setup::write_config(
            root.join(name),
            corridor,
            "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
        )
        .unwrap();
    }

    #[test]
    fn a_flat_layout_bot_exports_the_paths_it_actually_has() {
        // Normalising this bot to ./bot1/stitch.toml would name a path that
        // doesn't exist, and `docker compose up` turns a missing bind source into
        // an empty root-owned directory — so the config mount would land as a
        // directory and the bot would never start. The recovery file has to
        // reproduce what runs today.
        let (cfg, root) = test_cfg("flat");
        let corridor = setup::find_corridor("cngn-usdt-bsc").unwrap();
        std::fs::write(root.join("stitch.bot1.toml"), corridor.toml_template).unwrap();
        std::fs::write(
            root.join("stitch.bot1.key"),
            "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80\n",
        )
        .unwrap();

        let mut c = container("stitch-bot1", ContainerState::Running);
        c.labels.insert(LABEL_COMPOSE_SERVICE.into(), "bot1".into());
        c.mounts = flat_layout_mounts("/host/stitch", "bot1");

        let fleet = discover(&[c], &cfg);
        assert_eq!(fleet.get("bot1").unwrap().layout, Layout::FlatFiles);
        let yaml = render(&fleet, &cfg);

        assert!(yaml.contains("  bot1:\n"), "{yaml}");
        assert!(
            yaml.contains("./stitch.bot1.toml:/home/stitch/run/stitch.toml:ro"),
            "{yaml}"
        );
        assert!(
            yaml.contains("./stitch.bot1.key:/home/stitch/run/stitch.key:ro"),
            "{yaml}"
        );
        // Nothing may point at the per-bot directory it doesn't have.
        assert!(!yaml.contains("./bot1/"), "{yaml}");
        // No writable mount, so the ledger note must not be claimed here.
        assert!(!yaml.contains("persists the nonce ledger"), "{yaml}");
        // And the export says what that costs and how to fix it.
        assert!(yaml.contains("migrate it in the panel"), "{yaml}");
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn exports_panel_native_and_adopted_bots_together() {
        let (cfg, root) = test_cfg("both");
        seed(&root, "bot-a");
        seed(&root, "bot-b");

        let mut native = container("stitch-bot-a", ContainerState::Running);
        native.labels.insert(LABEL_BOT.into(), "bot-a".into());
        native.mounts = dir_layout_mounts("/host/stitch/bot-a");

        let mut adopted = container("stitch-bot-b", ContainerState::Running);
        adopted
            .labels
            .insert(LABEL_COMPOSE_SERVICE.into(), "bot-b".into());
        adopted
            .labels
            .insert(LABEL_COMPOSE_PROJECT.into(), "stitch".into());
        adopted.mounts = dir_layout_mounts("/host/stitch/bot-b");

        let fleet = discover(&[native, adopted], &cfg);
        let yaml = render(&fleet, &cfg);

        assert!(yaml.contains("  bot-a:\n"));
        assert!(yaml.contains("  bot-b:\n"));
        assert!(yaml.contains("container_name: stitch-bot-a"));
        assert!(yaml.contains("x-stitch: &stitch"));
        // The bot only checks for shutdown between ticks, so a recovery file that
        // leaves compose on its 10s default would kill it mid-tick on every
        // `docker compose stop`.
        assert!(yaml.contains("stop_grace_period: 30s"), "{yaml}");
        assert!(yaml.contains("<<: *stitch"));
        // The adopted one says where it came from.
        assert!(yaml.contains("Adopted from compose project \"stitch\""));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn volumes_are_relative_and_keep_the_ledger_persisting_layout() {
        let (cfg, root) = test_cfg("vols");
        seed(&root, "bot-a");
        let mut c = container("stitch-bot-a", ContainerState::Running);
        c.labels.insert(LABEL_BOT.into(), "bot-a".into());
        c.mounts = dir_layout_mounts("/host/stitch/bot-a");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        assert!(yaml.contains("- ./bot-a:/home/stitch/run"));
        assert!(yaml.contains("- ./bot-a/stitch.toml:/home/stitch/run/stitch.toml:ro"));
        assert!(yaml.contains("- ./bot-a/stitch.key:/home/stitch/run/stitch.key:ro"));
        // An absolute host path would not survive being copied to a new host.
        assert!(
            !yaml.contains("/host/stitch/bot-a:"),
            "paths must be relative to the compose file"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_stopped_bot_is_not_brought_back_up_by_the_recovery_command() {
        // The header tells the operator to run `docker compose up -d`, and that
        // starts every service in the file. A bot someone stopped deliberately
        // must not come back on the book because the fleet was restored.
        let (cfg, root) = test_cfg("stopped");
        seed(&root, "live");
        seed(&root, "paused");

        let mut live = container("stitch-live", ContainerState::Running);
        live.labels.insert(LABEL_BOT.into(), "live".into());
        live.mounts = dir_layout_mounts("/host/stitch/live");

        let mut paused = container("stitch-paused", ContainerState::Exited);
        paused.labels.insert(LABEL_BOT.into(), "paused".into());
        paused.mounts = dir_layout_mounts("/host/stitch/paused");

        let yaml = render(&discover(&[live, paused], &cfg), &cfg);
        let key = "\n    profiles: [stopped]\n";
        assert_eq!(
            yaml.matches(key).count(),
            1,
            "only the stopped bot is held back: {yaml}"
        );
        // And it's under that bot, not the running one.
        let paused_at = yaml.find("\n  paused:").unwrap();
        let live_at = yaml.find("\n  live:").unwrap();
        assert!(yaml.find(key).unwrap() > paused_at.max(live_at), "{yaml}");
        // The service itself is still fully described, so it can be started.
        assert!(yaml.contains("- ./paused:/home/stitch/run"), "{yaml}");
        assert!(
            yaml.contains("docker compose --profile stopped up -d paused"),
            "{yaml}"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_bot_pinned_to_another_image_keeps_it() {
        // The anchor carries the panel's image. Recovering from this file has to
        // bring each bot back on the binary it was running, not silently upgrade
        // the ones an operator pinned somewhere else.
        let (cfg, root) = test_cfg("pinned");
        seed(&root, "bot-a");
        seed(&root, "bot-b");

        let mut same = container("stitch-bot-a", ContainerState::Running);
        same.labels.insert(LABEL_BOT.into(), "bot-a".into());
        same.mounts = dir_layout_mounts("/host/stitch/bot-a");
        same.image = cfg.bot_image.clone();

        let mut pinned = container("stitch-bot-b", ContainerState::Running);
        pinned.labels.insert(LABEL_BOT.into(), "bot-b".into());
        pinned.mounts = dir_layout_mounts("/host/stitch/bot-b");
        pinned.image = "ghcr.io/acme/stitch-fork:v9".into();

        let yaml = render(&discover(&[same, pinned], &cfg), &cfg);
        assert!(
            yaml.contains("image: ghcr.io/acme/stitch-fork:v9"),
            "{yaml}"
        );
        // The one already on the panel's image inherits it from the anchor rather
        // than repeating it.
        assert_eq!(
            yaml.matches("image: ").count(),
            2,
            "only the anchor and the pinned bot should name an image: {yaml}"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn the_header_says_the_file_is_generated_and_one_way() {
        let (cfg, root) = test_cfg("header");
        let yaml = render(&Fleet::default(), &cfg);
        assert!(yaml.contains("Generated by the Stitch admin panel"));
        assert!(yaml.contains("never reads it"));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn an_empty_fleet_still_produces_parseable_yaml() {
        // `services:` with nothing under it is invalid YAML-as-compose; an empty
        // mapping keeps the file loadable.
        let (cfg, root) = test_cfg("empty");
        let yaml = render(&Fleet::default(), &cfg);
        assert!(yaml.contains("services:\n  {}"));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_bot_whose_config_is_unreadable_is_commented_not_dropped() {
        // Silently omitting it would make the export look complete while leaving
        // a bot out of the recovery path.
        let (cfg, root) = test_cfg("unreadable");
        let mut c = container("stitch-bot-x", ContainerState::Running);
        c.labels.insert(LABEL_BOT.into(), "bot-x".into());
        c.mounts = dir_layout_mounts("/somewhere/else/bot-x");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        assert!(yaml.contains("# bot-x was not exported"));
        assert!(yaml.contains("can't read its config file"), "{yaml}");
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_bot_name_that_isnt_a_valid_service_key_is_refused() {
        let (cfg, root) = test_cfg("badname");
        // An adopted compose service could be named anything.
        let mut c = container("weird", ContainerState::Running);
        c.labels
            .insert(LABEL_COMPOSE_SERVICE.into(), "Bad Name!".into());
        c.mounts = dir_layout_mounts("/host/stitch/whatever");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        assert!(yaml.contains("was not exported"));
        assert!(
            !yaml.contains("  Bad Name!:"),
            "an unsafe name must not reach the YAML as a key"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn signer_env_is_rendered_as_a_compose_mapping() {
        let (cfg, root) = test_cfg("env");
        seed(&root, "bot-a");
        let mut c = container("stitch-bot-a", ContainerState::Running);
        c.labels.insert(LABEL_BOT.into(), "bot-a".into());
        c.mounts = dir_layout_mounts("/host/stitch/bot-a");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        assert!(yaml.contains("RUST_LOG: info"));
        assert!(yaml.contains("STITCH_PRIVATE_KEY_FILE: /home/stitch/run/stitch.key"));
        // Never the secret itself.
        assert!(!yaml.contains("0xac0974"));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn one_bad_field_does_not_turn_a_turnkey_bot_into_a_hot_wallet() {
        // The whole point of this file is recovery, so a service block that looks
        // fine and then can't start on the fresh host is the worst outcome. The
        // signer table stands alone and is read alone, so an unrelated invalid field
        // can't downgrade it.
        let (cfg, root) = test_cfg("brokensigner");
        let corridor = crate::setup::find_corridor("cngn-usdt-bsc").unwrap();
        let toml = format!(
            "{}\n[signer]\nprovider = \"turnkey\"\norganization_id = \"org-1\"\n\
             sign_with = \"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\"\n\
             operator_address = \"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\"\n",
            corridor
                .toml_template
                .replace("tick_interval_secs = 5", "tick_interval_secs = \"soon\"")
        );
        std::fs::create_dir_all(root.join("bot-a")).unwrap();
        std::fs::write(root.join("bot-a").join("stitch.toml"), &toml).unwrap();
        // The loader really does reject this config, which is what used to make the
        // signer read as local.
        assert!(crate::config::Config::from_toml(&toml).is_err());

        let mut c = container("stitch-bot-a", ContainerState::Running);
        c.labels.insert(LABEL_BOT.into(), "bot-a".into());
        c.mounts = dir_layout_mounts("/host/stitch/bot-a");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        assert!(
            yaml.contains("TURNKEY_API_PRIVATE_KEY_FILE"),
            "the real signer has to survive one bad field: {yaml}"
        );
        assert!(
            !yaml.contains("STITCH_PRIVATE_KEY_FILE"),
            "it must not be exported as a hot wallet: {yaml}"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_bot_whose_signer_cannot_be_determined_at_all_is_omitted() {
        // Syntactically broken TOML: there is no signer table to recover, so the
        // panel says so rather than picking one and baking in the wrong mounts.
        let (cfg, root) = test_cfg("nosigner");
        std::fs::create_dir_all(root.join("bot-a")).unwrap();
        std::fs::write(root.join("bot-a").join("stitch.toml"), "this is not [ toml").unwrap();

        let mut c = container("stitch-bot-a", ContainerState::Running);
        c.labels.insert(LABEL_BOT.into(), "bot-a".into());
        c.mounts = dir_layout_mounts("/host/stitch/bot-a");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        assert!(yaml.contains("# bot-a was not exported:"), "{yaml}");
        assert!(yaml.contains("which signer"), "{yaml}");
        assert!(!yaml.contains("\n  bot-a:"), "no service block: {yaml}");
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn an_adopted_bot_is_exported_under_the_directory_it_actually_mounts() {
        // Inventory names an adopted bot after its compose service, which need not
        // match the directory it mounts. Synthesising `./<name>` produced a recovery
        // file pointing at paths that don't exist — nothing is renamed at export time.
        let (cfg, root) = test_cfg("adopted-dir");
        seed(&root, "custom");
        let mut c = container("stitch-foo", ContainerState::Running);
        c.labels.insert(LABEL_COMPOSE_SERVICE.into(), "foo".into());
        // Service `foo`, directory `custom`.
        c.mounts = dir_layout_mounts(&root.join("custom").display().to_string());
        let fleet = discover(&[c], &cfg);
        let bot = fleet.get("foo").expect("named after the compose service");
        assert_eq!(bot.layout, Layout::Directory);

        let yaml = render(&fleet, &cfg);
        // The service is still `foo:`, but its mounts name the real directory.
        assert!(yaml.contains("\n  foo:"), "{yaml}");
        assert!(yaml.contains("- ./custom:/home/stitch/run"), "{yaml}");
        assert!(
            !yaml.contains("./foo/") && !yaml.contains("- ./foo:"),
            "the service name is not a directory: {yaml}"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_config_outside_the_bots_root_is_exported_absolute_with_a_warning() {
        // It can't be written relative to the compose file, and an absolute path is
        // the only faithful answer — it works on this host. The comment is there
        // because it's the one line that won't survive being copied elsewhere.
        let (cfg, root) = test_cfg("outside-root");
        let elsewhere = root.join("elsewhere");
        seed(&elsewhere, "bot-a");
        // The panel's bots root is `root`; this bot's config lives outside it.
        let mut cfg = cfg;
        cfg.host_bots_dir = root.join("bots");
        cfg.bots_dir = root.clone();

        let mut c = container("stitch-bot-a", ContainerState::Running);
        c.labels.insert(LABEL_BOT.into(), "bot-a".into());
        c.mounts = dir_layout_mounts(&elsewhere.join("bot-a").display().to_string());
        let yaml = render(&discover(&[c], &cfg), &cfg);

        let abs = elsewhere.join("bot-a").display().to_string();
        assert!(
            yaml.contains(&format!("- {abs}:/home/stitch/run")),
            "{yaml}"
        );
        assert!(yaml.contains("outside"), "{yaml}");
        assert!(yaml.contains("another machine"), "{yaml}");
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn a_crash_looping_bot_is_exported_in_the_default_set() {
        // `restarting` isn't quoting this instant, but it's a bot the operator means
        // to have up — and the export is often taken precisely to recover onto a host
        // where it will work. Holding it back would quietly not bring it back.
        let (cfg, root) = test_cfg("restarting");
        seed(&root, "looping");
        let mut c = container("stitch-looping", ContainerState::Restarting);
        c.labels.insert(LABEL_BOT.into(), "looping".into());
        c.mounts = dir_layout_mounts("/host/stitch/looping");

        let yaml = render(&discover(&[c], &cfg), &cfg);
        // The service-level key, not the header's explanation of it.
        assert!(
            !yaml.contains("\n    profiles: [stopped]\n"),
            "a bot meant to be up must not be held back: {yaml}"
        );
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn scalars_that_yaml_would_reinterpret_get_quoted() {
        // An image tag like "1.0" would otherwise load as a float, and "no" as a
        // boolean.
        assert_eq!(yaml_scalar("1.0"), "'1.0'");
        assert_eq!(yaml_scalar("no"), "'no'");
        assert_eq!(yaml_scalar("true"), "'true'");
        assert_eq!(yaml_scalar(""), "''");
        assert_eq!(yaml_scalar(" leading"), "' leading'");
        assert_eq!(yaml_scalar("*anchor"), "'*anchor'");
        assert_eq!(yaml_scalar("a: b"), "'a: b'");
        // Ordinary values are left bare, which keeps the file readable.
        assert_eq!(yaml_scalar("info"), "info");
        assert_eq!(
            yaml_scalar("ghcr.io/textile-protocol/textile-stitch:latest"),
            "ghcr.io/textile-protocol/textile-stitch:latest"
        );
        // An embedded quote is doubled, YAML's own escape.
        assert_eq!(yaml_scalar("it's"), "'it''s'");
    }

    #[test]
    fn a_newline_cannot_escape_a_generated_comment() {
        assert_eq!(yaml_comment("a\nb: c"), "a b: c");
    }
}
